# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GbpD2mD2f_xbQkEFc_oYNwwDHU4Njn3O
"""

if st.button("Predict"):
    try:
        input_data = np.array([[hours, previous, extra, sleep, papers]])
        input_scaled = scaler.transform(input_data)
        prediction = model.predict(input_scaled)
        labels = ['Excellent', 'High', 'Low', 'Medium']
        st.success("Predicted Performance: " + labels[int(prediction[0])])
    except Exception as e:
        st.error(str(e))